export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as Login } from './Login/Login'
export { default as CreateRecord } from './CreateRecord/CreateRecord'
export { default as Record } from './Record/Record'
export { default as EditRecord } from './EditRecord/EditRecord'